<?php
/**
 * @description Particles template
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 */
?>

<?php
/** @formatter:off */
?>

<?php
/**
 * @var \D3p1\Particles\Block\View\Element\Html\Particles $block
 */
?>

<div id="<?php echo $block->getElementId(); ?>"></div>

<script type="text/x-magento-init">
{
    "#<?php echo $block->getElementId(); ?>": {
        "particles": <?php echo $block->getParticlesConfigJson(); ?>
    }
}
</script>